files:
  - source: /
    ignore:
      - /css
      - /elements
      - /img
      - /translations/it
      - /errors
      - README.md
      - LICENSE
    translation: /translations/%two_letters_code%/%original_file_name%
